name: CI [Ubuntu] beta

on: [workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Unzipper
      run: sudo apt-get install unzip -y
    - name: Download
      run: wget -O ngrok.zip https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-arm.zip
    - name: Extract
      run: unzip ngrok.zip
    - name: Install Libraries
      run: |
       sudo apt install snapd
       sudo apt install openssh-server
       sudo systemctl status ssh
    - name: Adding Architecture amd64
      run: |
       sudo apt update
       sudo apt install -y qemu-user-static binfmt-support
       sudo dpkg --add-architecture amd64
       sudo apt update
       sudo apt install libc6:amd64
    - name: Creating New User
      run: |
        user=dd-admin
        password=Dd-admin
        sudo adduser --quiet --disabled-password --shell /bin/bash --home /home/$user --gecos "User" $user
        # set password
        echo "$user:$password" | sudo chpasswd
        echo User: $user has been created with password: $password
        sudo usermod -aG sudo $user
        #SCRIPT END
    - name: Config RDP in Ubuntu(XRDP)
      run: |
       sudo apt-get install xrdp
       sudo systemctl status xrdp
       sudo apt-get install xfce4
       sudo apt-get install xfce4-terminal
       sudo sed -i.bak '/fi/a #xrdp multiple users configuration \n xfce-session \n' /etc/xrdp/startwm.sh
       sudo adduser xrdp ssl-cert
       sudo ufw allow 3389/tcp
       sudo /etc/init.d/xrdp restart
    - name: Config Of XRDP vim
      run: |
       sudo apt install nano -y
       echo `cat /etc/xrdp/xrdp.ini`
    - name: Make Ngrok Executable
      run: sudo cp ./ngrok /usr/bin/ngrok
    - name: Auth
      run: ngrok authtoken 2azo1E8SKKQSofEWm28vtkJGgfm_79G8n9bvHLB2RvPFTXQDV
#      run: ngrok config add-authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Create Tunnel
      run: ngrok tcp 3389
