
name: CI [MacOS]

on: [workflow_dispatch]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Install Brew
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        echo 'eval $(/opt/homebrew/bin/brew shellenv)' >> ~/.zprofile
        eval $(/opt/homebrew/bin/brew shellenv)
    - name: Install Ngrok
      run: |
        brew install unzip
        brew install --cask ngrok
    - name: Ngrok Auth
      run: ngrok authtoken 2azo1E8SKKQSofEWm28vtkJGgfm_79G8n9bvHLB2RvPFTXQDV
