# https://github.com/dikeckaan/MacOS-Workflow-VNC
# https://gist.github.com/nateware/3915757?permalink_comment_id=3369670

name: CI Mac-OS
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v2
