name: CI [Ubuntu]

on: [workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Unzipper
      run: sudo apt-get install unzip -y
    - name: Download
      run: wget -O ngrok.zip https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-arm.zip
    - name: Extract
      run: unzip ngrok.zip
    - name: Adding Architecture
      run: |
       sudo apt update
       sudo apt install -y qemu-user-static binfmt-support
       sudo dpkg --add-architecture amd64
       sudo apt update
       sudo apt install libc6:amd64
    - name: Make Ngrok Executable
      run: sudo cp ./ngrok /usr/bin/ngrok
    - name: Auth
      run: ngrok authtoken 2azo1E8SKKQSofEWm28vtkJGgfm_79G8n9bvHLB2RvPFTXQDV
#      run: ngrok config add-authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

#    - name: Enable TS
#      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
#    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
#    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
#    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
    - name: Create Tunnel
      run: ngrok tcp 22
