name: Tmate session on macOS

on: [push, pull_request]

jobs:
  tmate-session:
    runs-on: macos-latest

    steps:
      - name: Set up Tmate session
        run: |
          # Cài đặt tmate trên macOS
          brew install tmate

          # Tạo phiên tmate và in ra thông tin kết nối
          tmate -S /tmp/tmate.sock new-session -d
          tmate -S /tmp/tmate.sock wait tmate-ready
          echo "Tmate SSH: $(tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}')"
          echo "Tmate Web: $(tmate -S /tmp/tmate.sock display -p '#{tmate_web}')"

          # Duy trì phiên làm việc để người dùng có thể kết nối
          while true; do sleep 60; done
